import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "surface-variant": "#353435",
        "primary-fixed": "#e5e1e7",
        "primary": "#c8c5cb",
        "outline-variant": "#47464b",
        "on-tertiary": "#352f2c",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface": "#141313",
        "on-tertiary-container": "#7d7571",
        "surface-container-highest": "#353435",
        "tertiary-fixed-dim": "#cec5c0",
        "secondary-fixed": "#e4e1e6",
        "on-tertiary-fixed-variant": "#4c4542",
        "on-secondary-fixed-variant": "#47464a",
        "on-primary-fixed-variant": "#47464b",
        "primary-container": "#030305",
        "on-tertiary-fixed": "#1f1b18",
        "surface-container-low": "#1c1b1c",
        "inverse-primary": "#5f5e62",
        "inverse-surface": "#e5e2e1",
        "background": "#030305",
        "on-secondary": "#303033",
        "surface-dim": "#141313",
        "on-surface-variant": "#c8c5cb",
        "surface-container": "#201f20",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#1b1b1f",
        "on-secondary-fixed": "#1b1b1e",
        "tertiary": "#cec5c0",
        "primary-fixed-dim": "#c8c5cb",
        "inverse-on-surface": "#313030",
        "on-primary-container": "#77767b",
        "secondary": "#c8c5ca",
        "tertiary-container": "#050302",
        "secondary-container": "#47464a",
        "surface-container-high": "#2b2a2a",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ebe0db",
        "secondary-fixed-dim": "#c8c5ca",
        "on-secondary-container": "#b6b4b8",
        "on-primary": "#313034",
        "on-error": "#690005",
        "surface-tint": "#c8c5cb",
        "outline": "#929095",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "panel-padding": "16px",
        "gutter": "16px",
        "unit": "4px",
        "margin": "20px",
        "element-gap": "12px",
      },
      fontFamily: {
        "terminal-label": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "data-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "ui-body": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "data-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-25%)" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        marquee: "marquee 60s linear infinite",
        "fade-in": "fade-in 0.5s ease-out forwards",
      },
    },
  },
  plugins: [],
}

export default config
