"use client"

import React, { useEffect, useRef } from "react"
import { useMotionValue, useSpring, useTransform, motion } from "framer-motion"

interface RollingNumberProps {
  value: number
  prefix?: string
  suffix?: string
  decimals?: number
  className?: string
  currency?: boolean
  showSign?: boolean
}

/**
 * RollingNumber
 * 
 * A high-fidelity, spring-animated numeric display component.
 * Features:
 * - Institutional-grade Indian currency formatting (en-IN)
 * - Automatic polarity handling (showSign)
 * - Motion-smoothed transitions
 */
export function RollingNumber({
  value,
  prefix = "",
  suffix = "",
  decimals = 2,
  className = "",
  currency = false,
  showSign = false
}: RollingNumberProps) {
  // Ensure we are working with a clean numeric value
  const numericValue = typeof value === 'number' ? value : Number(value) || 0;
  
  const motionValue = useMotionValue(0)
  const springValue = useSpring(motionValue, {
    damping: 25,
    stiffness: 200,
  })

  useEffect(() => {
    motionValue.set(numericValue)
  }, [numericValue, motionValue])

  const displayValue = useTransform(springValue, (latest) => {
    const isNegative = latest < 0;
    // Defensive Math.abs to ensure no internal minus sign is generated by Intl.NumberFormat
    const absValue = Math.abs(Number(latest) || 0);

    const formatted = new Intl.NumberFormat('en-IN', {
      minimumFractionDigits: decimals,
      maximumFractionDigits: decimals,
    }).format(absValue);
    
    let finalPrefix = prefix;
    if (showSign) {
      if (isNegative) finalPrefix = `-${prefix}`;
      else if (latest > 0) finalPrefix = `+${prefix}`;
    } else if (isNegative) {
      // INSTITUTIONAL FIX: Always show negative sign even if showSign is false
      finalPrefix = `-${prefix}`;
    }

    return `${finalPrefix}${formatted}${suffix}`
  })

  const ref = useRef<HTMLSpanElement>(null)

  useEffect(() => {
    return displayValue.on("change", (latest) => {
      if (ref.current) {
        ref.current.textContent = latest
      }
    })
  }, [displayValue])

  return (
    <motion.span ref={ref} className={`whitespace-nowrap ${className}`}>
      {displayValue.get()}
    </motion.span>
  )
}
